config/routes.rb
Rails.application.routes.draw do

  mount Spree::Core::Engine, :at => '/'

  Spree::Core::Engine.add_routes do
    post '/orders/multi_populate', :to => 'taxon_orders#populate', :as => :multi_populate_orders
  end
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/spree/taxon_orders_controller.rb
module Spree
  # Copied from Spree::OrdersController to support #populate for
  # multiple/all products in a taxon [kit/bundle]
  class TaxonOrdersController < Spree::StoreController
    before_action :check_authorization
    rescue_from ActiveRecord::RecordNotFound, :with => :render_404
    helper 'spree/products', 'spree/orders'

    respond_to :html

    before_action :assign_order_with_lock, only: :update
    skip_before_action :verify_authenticity_token, only: [:populate]

    # Same a Spree::OrdersController#populate, but accepts a
    # params collection of "list_items" instead of just one at a time.
    def populate
      error    = nil
      order    = current_order(create_order_if_necessary: true)
      order.transaction do
        items    = params[:line_items] || []
        items.each do |index, item|
          variant  = Spree::Variant.find(item[:variant_id])
          quantity = item[:quantity].to_i
          options  = item[:options] || {}

          # 2,147,483,647 is crazy. See issue #2695.
          if quantity.between?(1, 2_147_483_647)
            begin
              order.contents.add(variant, quantity, options)
            rescue ActiveRecord::RecordInvalid => e
              error = e.record.errors.full_messages.join(", ")
            end
          else
            error = Spree.t(:please_enter_reasonable_quantity)
          end

          if error
            raise ActiveRecord::Rollback, "Some of the items could not be added to the order"
          end
        end
      end

      if error
        flash[:error] = error
        redirect_back_or_default(spree.root_path)
      else
        respond_with(order) do |format|
          format.html { redirect_to cart_path }
        end
      end
    end

    def check_authorization
      order = Spree::Order.find_by_number(params[:id]) || current_order

      if order
        authorize! :edit, order, cookies.signed[:guest_token]
      else
        authorize! :create, Spree::Order
      end
    end

    private

      def order_params
        if params[:order]
          params[:order].permit(*permitted_order_attributes)
        else
          {}
        end
      end

      def assign_order_with_lock
        @order = current_order(lock: true)
        unless @order
          flash[:error] = Spree.t(:order_not_found)
          redirect_to root_path and return
        end
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/spree/taxon_cache_helper.rb
module Spree
  module TaxonCacheHelper
    def cache_key_for_taxon_children(parent_permalink)
      kits = Spree::Taxon
        .select(:updated_at)
        .where(:permalink => parent_permalink)
        .first
        .children
      count = kits.count
      max_updated_at = (kits.map(&:updated_at).max || Date.today).to_s(:number)
      "#{I18n.locale}/#{current_currency}/spree/taxons/#{parent_permalink}-#{params[:page]}-#{max_updated_at}-#{count}"
    end
  end
end

app/views/admin/taxons/_images.html.erb
<%= f.field_container :hero, class: ['form-group'] do %>
  <%= f.label :hero, Spree.t(:hero_image) %>
  <%= f.file_field :hero %>
<% end %>

<%= f.field_container :group, class: ['form-group'] do %>
  <%= f.label :group, Spree.t(:group_image) %>
  <%= f.file_field :group %>
<% end %>

<%= f.field_container :style, class: ['form-group'] do %>
  <%= f.label :style, Spree.t(:style_image) %>
  <%= f.file_field :style %>
<% end %>

app/views/fix_home/index.html.erb
<header>

  <div class="masthead-elements-row-1">
    <div class="element-left"></div>
    <div class="element-middle">
      <%= image_tag "fix_home/fix-logotype.png", class:"logo", alt:"Fix" %>
      <br>
      <span class="logo-text">Fine Coffee Kits</span>
    </div>
    <div class="element-right">
      <div id="link-to-cart">
        <noscript>
          <%= link_to cart_path do %>
            <span class='glyphicon glyphicon-shopping-cart' title='<%= Spree.t(:shopping_cart) %>'></span>
          <% end %>
        </noscript>
        &nbsp;
      </div>
      <script>Spree.fetch_cart()</script>
    </div>
  </div>

  <div class="masthead-elements-row-2">
    <div class="element-middle">
      <%= link_to '/t/kit', class: "btn btn-default" do %>Browse Kits<% end %>
      <%= link_to '/products', class: "btn btn-trans" do %>Browse Products<% end %>
    </div>
  </div>

</header>
<section class="textured-section">

  <h1>Curated Coffee Components</h1>

  <ul class="products">
  <% cache(cache_key_for_taxon_children('featured')) do %>
    <%- Spree::Taxon
        .where(permalink: 'featured')
        .first
        .products.each do |product| -%>
      <li>
        <%= link_to product, class: "hot-link" do %>
          <%= large_image(product,  class: "product-image", alt: "") %>
          <h3 class="product-name"><%= product.name %></h3>
        <% end %>
        <div class="product-price"><%= product.display_price.to_html %></div>
        
        <%= form_for :order, url: populate_orders_path do |f| %>
          <%= hidden_field_tag "variant_id", product.master.id %>
          <%= hidden_field_tag "quantity", 1 %>
          <div class="kit-button"><%= button_tag type: :submit, class: "btn btn-hot" do %>
            Add to Cart
          <% end %></div>
        <% end %>
      </li>

    <%- end -%>
  <% end %>
  </ul>

</section>
<section>

  <h1>Complete Brewing Kits</h1>

  <ul class="kits">
  <% cache(cache_key_for_taxon_children('kit')) do %>
    <%- Spree::Taxon
        .where(permalink: 'kit')
        .first
        .children.each do |kit| -%>
      <li>
        <%= link_to seo_url(kit), class: "hot-link" do %>
          <% if kit.group_file_name %>
            <%= image_tag kit.group.url, class: "kit-image", alt: "" %>
          <% end %>
          <h3 class="kit-name"><%= kit.name %></h3>
        <% end %>
        <%- # Calculate kit prices
        taxon_total = kit.products.inject(0.0) do |sum, product| 
          product.price_in(current_currency).price + sum
        end
        taxon_price = Spree::Price.new(currency: current_currency)
        taxon_price.price = taxon_total
        -%>
        <div class="kit-price"><%= taxon_price.display_price.to_html %></div>

        <%= form_for :order, url: multi_populate_orders_path do |f| %>
          <%- kit.products.each_with_index do |product, i| -%>
            <%= hidden_field_tag "line_items[#{i}][variant_id]", product.master.id %>
            <%= hidden_field_tag "line_items[#{i}][quantity]", 1 %>
          <%- end -%>
          <div class="kit-button"><%= button_tag type: :submit, class: "btn btn-hot" do %>
            Add to Cart
          <% end %></div>
        <% end %>
      </li>

    <%- end -%>
  <% end %>
  </ul>

</section>
<footer>

  <div class="trailer-logo">
    <%= image_tag "fix_home/fix-logotype.png", class:"logo", alt:"Fix" %>
    <br>
    <span class="logo-text">Fine Coffee Kits</span>
  </div>

  <div class="trailer-links">
    <ul class="internal-links">
      <li><a href="https://heroku.github.io/fix">About</a></li>
      <li><a href="https://heroku.github.io/fix">Support</a></li>
      <li><a href="https://heroku.github.io/fix">Contact Us</a></li>
    </ul>
    <ul class="social-links">
      <li><a href="#">
        <%= image_tag "fix_home/social/twitter.png", class:"social-logo", alt:"" %>
        <span class="social-verb">Follow on</span>
        <span class="social-name">Twitter</span></a></li>
      <li><a href="#">
        <%= image_tag "fix_home/social/facebook.png", class:"social-logo", alt:"" %>
        <span class="social-verb">Like Us on</span>
        <span class="social-name">Facebook</span></a></li>
      <li><a href="#">
        <%= image_tag "fix_home/social/instagram.png", class:"social-logo", alt:"" %>
        <span class="social-verb">Follow on</span>
        <span class="social-name">Instagram</span></a></li>
    </ul>
  </div>

</footer>

app/views/spree/products/index.html.erb
<div class="stacked-block listing-page">
  <%= render partial: 'spree/shared/search' %>
  <%= render partial: 'spree/shared/products', locals: { products: @products } %>
</div>

app/views/spree/products/show.html.erb
<div data-hook="product_show" itemscope itemtype="https://schema.org/Product">
  <div class="col-md-6" data-hook="product_left_part">
    <div data-hook="product_left_part_wrap">
      <div id="product-images" data-hook="product_images">
        <div id="main-image" data-hook>

          <% if defined?(image) && image %>
            <%= image_tag image.attachment.url(:large), :itemprop => "image" %>
          <% else %>
            <%= large_image(@product, :itemprop => "image") %>
          <% end %>

        </div>
        <div id="thumbnails" data-hook>

          <%# no need for thumbnails unless there is more than one image %>
          <% if (@product.images + @product.variant_images).uniq.size > 1 %>
            <ul id="product-thumbnails" class="thumbnails list-inline" data-hook>
              <% @product.images.each do |i| %>
                <li class='tmb-all tmb-<%= i.viewable.id %>'>
                  <%= link_to(image_tag(i.attachment.url(:mini), class: "thumbnail"), i.attachment.url(:large)) %>
                </li>
              <% end %>

              <% if @product.has_variants? %>
                <% @product.variant_images.each do |i| %>
                  <% next if @product.images.include?(i) %>
                  <li class='vtmb tmb-<%= i.viewable.id %>'>
                    <%= link_to(image_tag(i.attachment.url(:mini), class: "thumbnail"), i.attachment.url(:large)) %>
                  </li>
                <% end %>
              <% end %>
            </ul>
          <% end %>

        </div>
      </div>
    </div>
  </div>

  <div class="col-md-6" data-hook="product_right_part">
    <div data-hook="product_right_part_wrap">
      <div id="product-description" data-hook="product_description">
        <h1 class="product-title stacked-block" itemprop="name">
        <%= @product.name %>
        <%- if @taxon -%>
          <div class="taxon-scope">
            &rarr; <%= link_to @taxon.name, seo_url(@taxon), :class => 'hero-image-link' %>
          </div>
        <%- end -%>
        </h1>

        <div itemprop="description" class="stacked-block" data-hook="description">
          <%= product_description(@product) rescue Spree.t(:product_has_no_description) %>
        </div>

        <div id="cart-form" class="stacked-block" data-hook="cart_form">
          <%= render :partial => 'cart_form' %>
        </div>

        <div class="stacked-block" data-hook="product_properties">
          <% unless @product_properties.empty? %>  
            <table id="product-properties" class="table" data-hook>
              <tbody>
                <% @product_properties.each do |product_property| %>
                  <% css_class = cycle('even', 'odd', :name => "properties") %>
                  <tr>
                    <th><%= product_property.property.presentation %></th>
                    <td><%= product_property.value %></td>
                  </tr>
                <% end %>
                <% reset_cycle('properties') %>
              </tbody>
            </table>
          <% end %>
        </div>

        <div class="stacked-block" data-hook="promotions">
          <%= render :partial => 'promotions' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/spree/shared/_link_to_cart.html.erb
<%= render template: 'spree/store/cart_link' %>

app/views/spree/shared/_main_nav_bar.html.erb
<div class="row">
  <nav class="col-md-12">
    <div id="main-nav-bar" class="navbar">
      <ul class="nav navbar-nav navbar-right" data-hook>
        <%- unless current_page?(cart_path) -%>
        <li id="link-to-cart" data-hook>
          <noscript>
            <%= link_to cart_path do %>
              <span class='glyphicon glyphicon-shopping-cart' title='<%= Spree.t(:shopping_cart) %>'></span>
            <% end %>
          </noscript>
          &nbsp;
        </li>
        <script>Spree.fetch_cart()</script>
        <%- end -%>
        <% if spree_current_user %>
          <li><%= link_to spree.logout_path do %>
            <span class='glyphicon glyphicon-log-out' title='<%= Spree.t(:logout) %>'></span>
          <% end %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</div>

app/views/spree/store/cart_link.html.erb
<%- if simple_current_order && !simple_current_order.item_count.zero? -%>
  <%= link_to spree.cart_path do -%>
    <span class='glyphicon glyphicon-shopping-cart' title='<%= Spree.t(:shopping_cart) %>'></span>
    (<%= simple_current_order.item_count %>)
  <%- end -%>
<%- end -%>

app/views/spree/taxons/show.html.erb
<% if @taxon.children.empty? %>
  <% if @taxon.hero_file_name %>
    <div class='stacked-block'>
      <div class='row'>
        <div class='hero-image col-sm-8'>
          <%= image_tag @taxon.hero.url %>
        </div>
        <div class='col-sm-4'>
          <div class="row stacked-block">
            <div class="col-xs-12">
              <h1 class="taxon-title"><%= @taxon.name %></h1>
            </div>
          </div>
          <div itemprop="description" class="stacked-block" data-hook="description">
            <%= product_description(@taxon) rescue Spree.t(:product_has_no_description) %>
          </div>
          <%= render partial: 'white_label/taxons/add_to_cart' %>
        </div>
      </div>
    </div>
  <% else %>
    <div class="taxon-header stacked-block">
      <div class="row">
        <div class="col-xs-12">
          <h1 class="taxon-title"><%= @taxon.name %></h1>
        </div>
      </div>
      <%= render partial: 'white_label/taxons/add_to_cart' %>
    </div>
  <% end %>
  
  <div class="stacked-block" data-hook="taxon_products">
    <%= render partial: 'spree/shared/products', locals: { products: @products, taxon: @taxon } %>
  </div>
<% end %>

<% unless params[:keywords].present? %>
  <div class="stacked-block" data-hook="taxon_children">
    <% cache [I18n.locale, @taxon] do %>
      <%= render partial: 'taxon', collection: @taxon.children %>
    <% end %>
  </div>
<% end %>

app/views/white_label/orders/_cart_buttons.html.erb
<div class="links col-md-6 navbar-form pull-right text-right" data-hook="cart_buttons">
  <div class="form-group">
    <%= button_tag class: 'btn btn-default', id: 'update-button' do %>
      <%= Spree.t(:update) %>
    <% end %>
    <%= button_tag class: 'btn btn-primary', id: 'checkout-link', name: 'checkout' do %>
      <%= Spree.t(:checkout) %>
    <% end %>
  </div>
</div>

app/views/white_label/orders/_cart_is_empty.html.erb
<div data-hook="empty_cart">
  <div class="alert alert-danger"><%= Spree.t(:your_cart_is_empty) %></div>
  <p><%= link_to Spree.t(:continue_shopping), root_path, class: 'btn btn-default' %></p>
</div>

app/views/white_label/orders/_cart_item_description.html.erb
<td class="cart-item-description" data-hook="cart_item_description">
  <p><%= link_to line_item.name, product_path(variant.product) %></p>
  <%= variant.options_text %>
  <% if line_item.insufficient_stock? %>
    <span class="out-of-stock">
      <%= Spree.t(:out_of_stock) %>&nbsp;&nbsp;<br />
    </span>
  <% end %>
</td>

app/views/white_label/orders/_cart_item_price.html.erb
<td class="cart-item-price" data-hook="cart_item_price">
  <%= line_item.single_money.to_html %>
</td>

app/views/white_label/orders/_cart_item_total.html.erb
<td class="cart-item-total" data-hook="cart_item_total">
  <%= line_item.display_amount.to_html unless line_item.quantity.nil? %>
</td>

app/views/white_label/orders/_cart_secondary_buttons.html.erb
<div id="empty-cart" class="col-md-6 pull-left navbar-form" data-hook>
  <%= form_tag empty_cart_path, method: :put do %>
    <p id="clear_cart_link" data-hook>
      <%= submit_tag Spree.t(:empty_cart), class: 'btn btn-default' %>
      <%= link_to Spree.t(:continue_shopping), root_path, class: 'continue btn btn-default' %>
    </p>
  <% end %>
</div>

app/views/white_label/orders/_cart_title.html.erb
<h1 class='iconic-cart-title'><span class='glyphicon glyphicon-shopping-cart' title='<%= Spree.t(:shopping_cart) %>'></span></h1>

app/views/white_label/orders/_cart_total.html.erb
<tr class="cart-total">
  <th colspan="4" class="cart-total-label"><%= Spree.t(:total) %></th>
  <td><%= order_form.object.display_total %></td>
  <td></td>
</tr>

app/views/white_label/orders/_order_item_description.html.erb
<td data-hook="order_item_description">
  <h4><%= item.variant.product.name %></h4>
  <%= "(" + item.variant.options_text + ")" unless item.variant.option_values.empty? %>
</td>

app/views/white_label/products/_price_add_to_cart.html.erb
<div id="product-price" class="col-xs-6">
  <div>
    <span class="price selling" itemprop="price">
      <%= display_price(@product) %>
    </span>
    <span itemprop="priceCurrency" content="<%= @product.currency %>"></span>
  </div>

  <% if @product.master.can_supply? %>
    <link itemprop="availability" href="https://schema.org/InStock" />
  <% elsif @product.variants.empty? %>
    <div class="out-of-stock"><%= Spree.t(:out_of_stock) %></div>
  <% end %>
</div>

<div class="add-to-cart col-xs-6">
  <%= hidden_field_tag :quantity, 1 %>
  <%= button_tag :class => 'btn btn-default', :id => 'add-to-cart-button', :type => :submit do %>
    <%= Spree.t(:add_to_cart) %>
  <% end %>
</div>

app/views/white_label/shared/_head.html.erb
<link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600' rel='stylesheet' type='text/css'>

app/views/white_label/shared/_header.html.erb
<div id="white-label-header">
  <header id="header" data-hook>
    <div class="container">
      <div class="row">
        <div class="col-xs-4">
          <%= render :partial => 'spree/shared/nav_bar' %>
        </div>
        <figure id="logo" class="col-xs-4" data-hook>
          <%= logo %>
        </figure>
        <div class="col-xs-4">
          <%= render :partial => 'spree/shared/main_nav_bar' if store_menu? %>
        </div>
      </div>
    </div>
  </header>
</div>

app/views/white_label/shared/_products_list_item.html.erb
<div id="product_<%= product.id %>" class="col-lg-4 col-sm-6 product-list-item" data-hook="products_list_item" itemscope itemtype="https://schema.org/Product">
  <% cache(@taxon.present? ? [I18n.locale, current_currency, @taxon, product] : [I18n.locale, current_currency, product]) do %>
    <div class="row">
      <div class="product-list-item-display col-xs-6">
        <%= link_to product_image(product, itemprop: "image", class: "product-list-item-image"), url, itemprop: 'url' %>
      </div>
      <div class="product-list-item-info col-xs-6">
        <h2><%= link_to truncate(product.name, length: 50), url, class: 'info', itemprop: "name", title: product.name %></h2>
        <div itemprop="offers" itemscope itemtype="https://schema.org/Offer">
          <span class="price selling" itemprop="price"><%= display_price(product) %></span>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/white_label/shared/_search_button.html.erb
<%= submit_tag Spree.t(:search), :name => nil, class: "btn btn-default" %>

app/views/white_label/shared/_top_nav_bar.html.erb
<div></div>

app/views/white_label/taxons/_add_to_cart.html.erb
<%= form_for :order,
  :url => multi_populate_orders_path,
  :html => { :class => 'taxon-add-to-cart stacked-block' } do |f| %>

  <div class="row">

    <div id="product-price" class="col-xs-6">
      <div>
        <span class="price selling" itemprop="price">
          <%- taxon_total = @products.inject(0.0) do |sum, product| 
            product.price_in(current_currency).price + sum
          end
          taxon_price = Spree::Price.new(currency: current_currency)
          taxon_price.price = taxon_total
          -%>
          <%= taxon_price.display_price.to_html %>
        </span>
        <span itemprop="priceCurrency" content="<%= current_currency %>"></span>
      </div>
    </div>

    <div class="add-to-cart col-xs-6">
      <%- @products.each_with_index do |product, i| -%>
        <%= hidden_field_tag "line_items[#{i}][variant_id]", product.master.id %>
        <%= hidden_field_tag "line_items[#{i}][quantity]", 1 %>
      <%- end -%>
      <%= button_tag :class => 'btn btn-default', :id => 'add-to-cart-button', :type => :submit do %>
        <%= Spree.t(:add_kit_to_cart) %>
      <% end %>
    </div>

  </div>

<% end %>

app/views/white_label/taxons/_taxon.html.erb
<div class="taxon taxon-listing" data-hook="taxon">
  <% if taxon.group_file_name %>
    <%= link_to seo_url(taxon), :class => 'hero-image-link' do %>
      <div class="row">
        <div class='hero-image' style="background-image: url(<%= taxon.style.url %>)">
          <div class='col-xs-5 col-xs-offset-7 col-sm-3 col-sm-offset-8'>
            <div class="group-link">
              <%= image_tag taxon.group.url %>
              <h1><%= taxon.name %></h1>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
    <h1 class="taxon-title"><%= link_to taxon.name, seo_url(taxon) %></h1>
  <% end %>
</div>